# R2Devops.io pipeline template - this template aims to generate a complete pipeline
#
# Inputs:
#   - List of technologies detected in the project : go, go checksums, go module, ignore list,

name: R2Devops
on:
  push:
    branches: [ main, myNewPipeline ]
  pull_request:
    branches: [ main ]

jobs:


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
