# R2Devops.io pipeline generation - this aims to be included in your pipeline
#
# Inputs:
#   - List of technologies detected in the project : go, go checksums, go module, ignore list, yaml,

name: R2Devops
on:
  push:
    branches: [ main, r2devops-autopipeline]
  pull_request:
    branches: [ main ]

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master


# R2DEVOPS - PROJECT CUSTOMIZATIONS
# You can update them in your settings :)

