# R2Devops.io pipeline generation
#
# List of technologies detected in the project : golang, yaml, 

name: R2Devops
on:
  push:
    branches: [ main, r2devops]
  pull_request:
    branches: [ main ]

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master


